//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export class ImageMetaData implements IImageMetaData {
    fileName?: string | undefined;
    url?: string | undefined;
    price?: number;
    licence?: string | undefined;
    usagePurpose?: UsagePurpose;
    tags?: string[] | undefined;
    projectName?: string | undefined;

    constructor(data?: IImageMetaData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.fileName = _data["fileName"];
            this.url = _data["url"];
            this.price = _data["price"];
            this.licence = _data["licence"];
            this.usagePurpose = _data["usagePurpose"];
            if (Array.isArray(_data["tags"])) {
                this.tags = [] as any;
                for (let item of _data["tags"])
                    this.tags!.push(item);
            }
            this.projectName = _data["projectName"];
        }
    }

    static fromJS(data: any): ImageMetaData {
        data = typeof data === 'object' ? data : {};
        let result = new ImageMetaData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fileName"] = this.fileName;
        data["url"] = this.url;
        data["price"] = this.price;
        data["licence"] = this.licence;
        data["usagePurpose"] = this.usagePurpose;
        if (Array.isArray(this.tags)) {
            data["tags"] = [];
            for (let item of this.tags)
                data["tags"].push(item);
        }
        data["projectName"] = this.projectName;
        return data;
    }
}

export interface IImageMetaData {
    fileName?: string | undefined;
    url?: string | undefined;
    price?: number;
    licence?: string | undefined;
    UsagePurpose?: UsagePurpose[] | undefined;
    tags?: string[] | undefined;
    projectName?: string | undefined;
}

export enum UsagePurpose {
  OnlineBanner = 'Banner Werbung',
  PrintMagazine = 'Print Magazine',
  PrintFlyer= 'Print Flyer',
  Video= 'Video Werbung',
}
